server:
  port: 8900
spring:
  application:
    name: mscloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YL10000/ms
          search-paths: /
          default-label: master
          # Error occured cloning to base directory.
          username: YL10000
          password: 784152120kl
          skip-ssl-validation: true
  rabbitmq:
    host: centos7-01
    port: 5672
    username: guest
    password: guest

# 配置需要暴露的接口
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"