server:
  port: 80
spring:
  application:
    name: mscloud-order-consumer
  # zipkin连接地址
  zipkin:
    base-url: http://centos7-01:9411
  sleuth:
    sampler:
      # 采样比例
      probability: 1
  cloud:
#    zookeeper:
#      # zookeeper注册中心的连接地址
#      connect-string: 192.168.0.162:2181

    # consul注册中心
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: localhost
      port: 8500

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9001/eureka/
#  instance:
#    instance-id: order-consumer
#    prefer-ip-address: true

logging:
  level:
    com.life.service.PaymentService: info

swagger:
  enable: true
feign:
  hystrix:
    enabled: true